name: SakuraPrefix
main: sakura.kooi.SakuraPrefix.SakuraPrefix
version: 5
author: Ldcr
depend: ["SakuraUtils"]
softdepend: ["SkinRestorer"]
commands:
  sakuraprefix:
    aliases: [prefix]
  nick:
permissions:
  sakuraprefix.edit:
    description: 修改称号的权限
    default: op
  sakuraprefix.nick:
    description: 更改自己Nick的权限
    default: op
  sakuraprefix.nick.force:
    description: 强行更改Nick无视黑名单与占用的权限
    default: false
  sakuraprefix.nick.bypass:
    description: 看见其他Nick玩家的权限
    default: op
